source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'PreventiviOS' do
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'Firebase'
end
